### ISSUE TITLE
How did you work around "vfs_map_name_to_handle_at :FSAL :DEBUG :Error Operation not permitted"?

### ISSUE THREAD

**Issue by boutell** [NicolasT/contained-ganesha#18]
Hi there,

No trouble with your container, just hoping for a hint.

I was trying to do something similar myself and eventually ran into this when trying to set up a very simple ganesha config with just NFSv4 support and VFS:

```
vfs_lookup_path :FSAL :DEBUG :filesystem / for path /test
vfs_map_name_to_handle_at :FSAL :DEBUG :Error Operation not permitted (1) bytes = 48
vfs_lookup_path :FSAL :CRIT :Could not get handle for path /test, error Operation not permitted
```

That led me to this:

https://github.com/nfs-ganesha/nfs-ganesha/issues/511

Which seems to say I'm definitely out of luck. But, you seem to be pulling it off.

Are you familiar with the error I'm talking about? Any workarounds?

Thanks!

**Comment by NicolasT** [comment]
Your container needs the `CAP_DAC_READ_SEARCH` capability so it can invoke `open_by_handle_at`, which I handle e.g. at https://github.com/NicolasT/contained-ganesha/blob/3a65296c532f9ea3951ed209348fa84467b147b9/deploy/docker-compose/docker-compose.yml#L125

See `open_by_handle_at(2)`, which says

> The caller must have the CAP_DAC_READ_SEARCH capability to invoke open_by_handle_at().

Note some other capabilities are required as well, cfr. https://github.com/NicolasT/contained-ganesha/blob/3a65296c532f9ea3951ed209348fa84467b147b9/deploy/docker-compose/docker-compose.yml#L120-L130

**Comment by boutell** [comment]
Thank you!

**Comment by NicolasT** [comment]
Y/w.
